// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDipYofBgulCyGxLcVrubcK4QMsK0vArBw',
    appId: '1:935932098814:web:988c9cfc0050ee2ca7cdaf',
    messagingSenderId: '935932098814',
    projectId: 'moizchat-e7a09',
    authDomain: 'moizchat-e7a09.firebaseapp.com',
    storageBucket: 'moizchat-e7a09.appspot.com',
    measurementId: 'G-KK1LQCSZTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8WX57VVhC63p9xTJngdJDuvedLuhyRss',
    appId: '1:935932098814:android:38956dd721dcc98ba7cdaf',
    messagingSenderId: '935932098814',
    projectId: 'moizchat-e7a09',
    storageBucket: 'moizchat-e7a09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCnf40GOxspGg67RREMH5y7Xa8xBwLp5U',
    appId: '1:935932098814:ios:4071dd42c6b0e990a7cdaf',
    messagingSenderId: '935932098814',
    projectId: 'moizchat-e7a09',
    storageBucket: 'moizchat-e7a09.appspot.com',
    iosClientId: '935932098814-701v0evqen2e107jte9bl44pgverjolm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCnf40GOxspGg67RREMH5y7Xa8xBwLp5U',
    appId: '1:935932098814:ios:57693dbc19aed378a7cdaf',
    messagingSenderId: '935932098814',
    projectId: 'moizchat-e7a09',
    storageBucket: 'moizchat-e7a09.appspot.com',
    iosClientId: '935932098814-k3f4nf624pi06oi9ovg0hm0okku0pq8m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
